spring.application.name=notification-service
server.port = 8084

spring.data.mongodb.uri=mongodb://localhost:27017/shiptrack

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

eureka.instance.instance-id=${spring.application.name}:${server.port}

jwt.secret=6G8qL2mP9wR4xT7vY1aN5kC8dF3hJ6sQ9zX2bV4nM7pR1tY5uW8eA3cD6fG9hK2

spring.jackson.default-property-inclusion=non_null

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false

kafka.topics.shipment-events=shipment-events



logging.level.com.shiptrack.notification_service=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.kafka=INFO
